name: Awesome Bot

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
  - cron: "0 3 1 * *"
  workflow_dispatch:

jobs:
  test:
    name: Run Awesome Bot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Install Awesome Bot
      run: gem install awesome_bot
    - name: Run Awesome Bot
      run: awesome_bot README.md --allow-ssl --allow-dupe --allow-redirect --allow 429 --white-list udemy.com,medium.com
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure()
      with:
        name: ab-results
        path: ab-results-README.md-filtered.json
